server:
  log_level: debug

metrics:
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://${REMOTE_WRITE_HOST:-localhost:9009}/api/prom/push
  configs:
    - name: default

logs:
  configs:
    - name: default
      clients:
        - url: http://${LOKI_HOST:-localhost:3100}/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml

traces:
  configs:
    - name: default
      remote_write:
        - endpoint: ${TEMPO_HOST:-localhost:4317}
          insecure: true
      receivers:
        otlp:
          protocols:
            grpc:

integrations:
  metrics:
    autoscrape:
      enable: true
      metrics_instance: default

  agent:
    extra_labels:
      cluster: docker-compose
      namespace: docker-compose
      container: grafana-agent
      pod: grafana-agent-${HOSTNAME:-example}

  app_agent_receiver:
    autoscrape:
      enable: true
      metrics_instance: default
    instance: rico
    logs_instance: default
    logs_labels:
      app: rico
      kind: ''
    logs_send_timeout: 5s
    server:
      api_key: api_key
      cors_allowed_origins:
        - '*'
        - http://localhost:5173
        - http://127.0.0.1:5173
      host: 0.0.0.0
      #      max_allowed_payload_size: 5e+05
      port: 8027
      rate_limiting:
        burstiness: 100
        enabled: true
        rps: 100
    sourcemaps:
      download: true
    traces_instance: default
