apiVersion: 1

deleteDatasources:
  - name: Cortex
  - name: Tempo
  - name: Loki

datasources:
  - name: Cortex
    type: prometheus
    access: proxy
    orgId: 1
    url: http://cortex:9009/api/prom
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: cortex
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TraceID

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: cortex

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id=(\w+)
          name: TraceID
          url: $${__value.raw}
