---
kind: pipeline
name: grafana-javascript-agent

steps:
- name: Install dependencies
  image: node:lts-stretch
  commands:
  - yarn install --frozen-lockfile

- name: Build
  image: node:lts-stretch
  commands:
  - yarn build

- name: Lint
  image: node:lts-stretch
  commands:
  - yarn quality

- name: E2E
  image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
  commands:
  - npx cypress install
  - yarn ci:e2e

- name: Publish
  image: node:lts-stretch
  commands:
  - git fetch --tags
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - yarn run publish from-git --yes --no-verify-access
  environment:
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  when:
    event:
    - tag
---
kind: signature
hmac: b35a62fc4a105dca81ae7b49d7525f0d0feba9804a15b739a1bfd238adbb9f28

...
